name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
env:
  CMAKE_VERSION: 3.20.2
  LLVM_VERSION: 14.0.0
  NDK_VERSION: r25b

jobs:
  linux_and_android:
    runs-on: ubuntu-latest
    steps:
    - name: checkout master
      uses: actions/checkout@master

    - name: init linux cross compile env
      run: |
        sh scripts/setup_linux_cross_compile.sh
        mkdir -p artifact
      shell: bash

    - name: compile linux
      run: |
        python3 scripts/platform_builder.py --platform=linux --arch=all --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION --llvm_dir=$HOME/opt/llvm-$LLVM_VERSION
        cp include/dobby.h build/linux
        tar -zcvf build/dobby-linux-all.tar.gz build/linux
        cp build/dobby-linux-all.tar.gz artifact/
        
      shell: bash
    
    - name: compile android
      run: |
        python3 scripts/platform_builder.py --platform=android --arch=all --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION --llvm_dir=$HOME/opt/llvm-$LLVM_VERSION --android_ndk_dir=$HOME/opt/ndk-$NDK_VERSION
        cp include/dobby.h build/android
        tar -zcvf build/dobby-android-all.tar.gz build/android
        cp build/dobby-android-all.tar.gz artifact/
      shell: bash

    - name: print output
      run: |
        ls -lha .

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dobby-build
        path: "build/"